### ISSUE TITLE
Allow using any available python

### ISSUE THREAD

**Issue by Kyle-Verhoog** [DataDog/riot#65]
Maybe something like

```
Venv(
  pys="*",
)
```

**Comment by brettlangdon** [comment]
What is the goal here?

Could also do `pys="3"`, or just not specifying at all?

Also curious about `pys="3.7.6"`, value in allowing any level of specificity?

**Comment by Kyle-Verhoog** [comment]
See #66 where it might come in handy. Although yes, in that case pys="3" should have worked actually 😆.


> Also curious about pys="3.7.6", value in allowing any level of specificity?

This should work at present. All it does is concatenate the number and "python" and looks for it on the PATH.

**Comment by jd** [comment]
Hmmmm not sure it's wise. That sounds like an easy way to shoot yourself in the foot thinking you are running against versions X Y Z when in the end it's not the case. 🤔

**Comment by brettlangdon** [comment]
not sure it is wise to support `x.y.z`?

probably agree, the only way we can know for sure is it we actually check the python version manually, since just the binary name isn't enough

**Comment by Kyle-Verhoog** [comment]
This is mostly addressed by #79 and there doesn't seem to be a need for specifying _any_ python.
